version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
      timezone: Asia/Tokyo
    ignore:
      - dependency-name: "@types/node"
        versions: ["25.x", "27.x", "29.x"]  # 奇数バージョン（非LTS）を無視
    allow:
      - dependency-type: all
    rebase-strategy: auto
    assignees:
      - poad
    groups:
      npm:
        patterns:
          - '*'
