packages:
  - ./app
  - ./cdk

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  vite@>=6.0.0 <=6.1.5: '>=6.1.6'
  vite@>=6.1.0 <6.1.5: '>=6.1.5'
