packages:
  - ./app
  - ./cdk

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

overrides:
  diff@<8.0.3: '>=8.0.3'
  esbuild@<=0.24.2: '>=0.27.0'
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
  h3@<=1.15.4: '>=1.15.5'
  seroval@<=1.4.0: '>=1.4.1'
  tar@<7.5.7: '>=7.5.7'
  vite@>=6.1.0 <6.1.5: '>=6.1.5'
  # eslint: ">=10.0.0"
  # '@eslint/js': ">=10.0.0"
  eslint: "^9"
  '@eslint/js': "^9"
  '@stylistic/eslint-plugin': '>=5.0.0'
