packages:
  - ./app
  - ./cdk
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver
overrides:
  esbuild@<=0.24.2: '>=0.25.0'
  vite@>=6.1.0 <6.1.5: '>=6.1.5'
  vite@>=6.0.0 <=6.1.5: '>=6.1.6'
